
spring:
  application:
    name: car-factory-auth
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/card-factory-auth
    username: sa
    password: Passw0rd
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: 8088
  
eureka:
  instance:
    hostname: "localhost"
  
shuaicj.security.jwt.secret: otherpeopledontknowit