spring:
  application:
    name: car-factory-employees
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  security:
    user:
      name: emre
      password: emre
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/card-factory-employees
    username: sa
    password: Passw0rd
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      
logging:
  level:
    org.springframework: info
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - env
          - metrics
          - prometheus
          
eureka:
  instance:
    hostname: "localhost"
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://emre:emre@localhost:8761/eureka/