spring:
  application:
    name: car-engine
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  security:    user:      name: emre      password: emre
        
logging:
  level:
    org.springframework: info
    io.github.resilience4j: debug
server:
  port: 8081
  
management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus
          
eureka:
  instance:
    hostname: "localhost"
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://emre:emre@localhost:8761/eureka/