spring:
  application:
    name: proxy-gateway


ribbon: 
  ReadTimeout: 60000

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    car-factory-auth:
      path: /getToken/**
      serviceId: car-factory-auth
      stripPrefix: false #önündeki 'getToken' path'ini kaldırmayacak, defaultta bu değer true olduğu için diğerlerinde prefix kaldıracak
    car-factory-auth-user:
      path: /car-factory-auth/**
      serviceId: car-factory-auth
      strip-prefix: false #önündeki '/car-factory-auth' path'ini kaldırmayacak, defaultta bu değer true olduğu için diğerlerinde prefix kaldıracak
    car-factory:
      path: /car-factory/**
      serviceId: car-factory
    car-engine:
      path: /car-engine/**
      serviceId: car-engine
    car-hood:
      path: /car-hood/**
      serviceId: car-hood
    car-factory-employees:
      path: /car-factory-employees/**
      serviceId: car-factory-employees

server:
  port: 8085  
  
eureka:
#  instance:#    hostname: "localhost"
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://emre:emre@localhost:8761/eureka
    healthcheck:
      enabled: true
      
logging:
  level:
    org.springframework: debug
    
