spring:
  application:
    name: car-hood
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  security:
    user:
      name: emre
      password: emre
logging:
  level:
    org.springframework: info
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - env
          - metrics
          - prometheus
          
eureka:
  instance:
    hostname: "localhost"
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://emre:emre@localhost:8761/eureka/