spring:
  application:
    name: car-factory
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  h2:    console:      enabled: true
      path: /h2-console
  datasource:    url: jdbc:h2:file:~/card-factory
    username: sa
    password: Passw0rd
    driver-class-name: org.h2.Driver
  jpa:    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:      ddl-auto: update
      
eureka:  instance:    hostname: "localhost"
     
      
logging:
  level:
    org.springframework: debug
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - env
          - metrics
          - prometheus